import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

interface IRouteModel {
  path: string;
  name: string;
}

let routes: IRouteModel[] = [
  {
    path: "/page0",
    name: "使用padding-left做的侧边栏 (仿arco-pro)",
  },
  {
    path: "/page1",
    name: "使用translate做的侧边栏 (yt视频)",
  },
  {
    path: "/page2",
    name: "一个普通的侧边栏与顶部导航条 (yt视频)",
  },
  {
    path: "/page3",
    name: "用translate和占位元素做的简易侧边栏 (仿vben)",
  },
  {
    path: "/page4",
    name: "使用max-height做的展开面板",
  },
  {
    path: "/page5",
    name: "做了一半的侧边栏菜单Demo (完全体在SolidHopeAdmin中)",
  },
  {
    path: "/page6",
    name: "人物展示卡片 (b站)",
  },
  {
    path: "/page7",
    name: "炫彩系列",
  },
  {
    path: "/page8",
    name: "文章区域滑动到底部的效果(twitter)",
  },
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pageBox">
        <div className="title">index</div>
        <div className="linkBox">
          {routes.map((item, index) => {
            return (
              <>
                <Link key={index} href={item.path} passHref>
                  <div className="linkDiv">
                    【{index}】 {item.name}
                  </div>
                </Link>
              </>
            );
          })}
        </div>
      </div>

      <style jsx>
        {`
          .title {
            @apply py-7 text-7xl;
            color: red;
          }
          .linkBox {
            @apply flex cursor-pointer  flex-col space-y-4 rounded-2xl;
          }

          .linkDiv {
            @apply rounded-xl border-4 border-purple-300 py-6 hover:bg-yellow-400 hover:text-purple-500;
          }

          .pageBox {
            @apply flex h-full w-full   flex-col p-5 text-center;
          }
        `}
      </style>
    </>
  );
};

export default Home;
